### ISSUE TITLE
Refreshing current page after initial load returns an Internal Server Error

### ISSUE THREAD

**Issue by spapaseit** [aurelia/pal-nodejs#32]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.12.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack ^4.1.1

* **Browser:**
all 
* **Language:**
ESNext

**Current behavior:**
Building an SSR-enabled site with aurelia, and after I've updated the `aurelia-cli` to version `1.0.0-beta.12` (both globally and with `--save-dev` I've started getting exceptions upon refreshing the page.

The first run of the site after `npm run server` works fine, hoewever, as soon as you press F5 to refresh whichever page you're on, the page only displays **`Internal server error`**, and I get one of two exceptions.

First I aways get this **aurelia-pal-nodejs** exception:
```

  TypeError: Cannot set property XMLHttpRequest of #<NodeJsPlatform> which has only a getter
      at Function.assign (<anonymous>)
      at aurelia_pal_1.initializePAL (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\aurelia-pal-nodejs\dist\index.js:18:16)
      at Object.initializePAL (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\aurelia-pal\dist\commonjs\aurelia-pal.js:96:3)
      at Object.initialize (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\aurelia-pal-nodejs\dist\index.js:17:19)
      at Object.151 (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:136916)
      at r (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:194)
      at Object.62 (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:409630)
      at r (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:194)
      at module.exports.0.t.__esModule (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:1219)
      at Object.<anonymous> (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\dist\server.bundle.js:1:1229)
      at Module._compile (module.js:653:30)
      at Object.Module._extensions..js (module.js:664:10)
      at Module.load (module.js:566:32)
      at tryModuleLoad (module.js:506:12)
      at Function.Module._load (module.js:498:3)
      at Module.require (module.js:597:17)
```

And if I press F5 again on the page, the **aurelia-ssr-engine** exception comes up ([I've made and issue on that repo as well](https://github.com/aurelia/ssr-engine/issues/11)):

```
  TypeError: Cannot read property 'reconfigure' of undefined
      at start (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\aurelia-ssr-engine\dist\commonjs\aurelia-ssr-engine.js:53:20)
      at render (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\aurelia-ssr-engine\dist\commonjs\aurelia-ssr-engine.js:25:12)
      at C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\custom-middleware-koa.js:14:12
      at app.use (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\server.js:85:9)
      at dispatch (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-compose\index.js:42:32)
      at app.use (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\server.js:57:16)
      at dispatch (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-compose\index.js:42:32)
      at app.use (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\server.js:38:18)
      at dispatch (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-compose\index.js:42:32)
      at C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-http-request\index.js:14:11
      at dispatch (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-compose\index.js:42:32)
      at serve (C:\Software Development\Projects\Gigantisch\TrappenGigant\TrappenGigant\node_modules\koa-static\index.js:53:15)
      at <anonymous>`
```

Note that I'm using two forks by @JeroenVinke (sorry for the tag, dude) of the `aurelia-ssr-engine` and `aurelia-ssr-bootstrapper-webpack`:

```javascript
"aurelia-ssr-bootstrapper-webpack": "github:JeroenVinke/ssr-bootstrapper-webpack-1#error-handling-build",
"aurelia-ssr-engine": "github:JeroenVinke/ssr-engine#meta-tags-build",
```

Also relevant might be the custom middleware for Koa that we use, which has been in place for months and has worked perfectly until this update of the cli:

```javascript
const {render} = require("aurelia-ssr-engine");

function aureliaKoaMiddleware (renderOptions, initializationOptions) {
  return function (ctx, next) {
    const url = ctx.request.URL;
    const pathname = url.pathname;

    // skip requests where urls have an extension
    const extensionMatcher = /^.*\.[^\\]+$/;
    if (pathname.match(extensionMatcher)) {
      return next();
    }

    return render(Object.assign({ url }, renderOptions), initializationOptions)
    .then((html) => {
      ctx.body = html;
    })
    .catch((e) => {
      // if there is an error, call next middleware (which serve the default html template without SSR)
      console.log(e);
      return next();
    });
  };
};

module.exports = {
  aureliaKoaMiddleware
};
```

**Expected/desired behavior:**

* **What is the expected behavior?**
I can refresh the page as many times as I want without getting exceptions

**Comment by Alexander-Taran** [comment]
@spapaseit mind closing this one?

**Comment by spapaseit** [comment]
@Alexander-Taran, sorry, yes, of course.

Done.
